import RNHTMLtoPDF from 'react-native-html-to-pdf';
import Share from 'react-native-share';
import { Expense, Income, Tenant, Flat, Owner, RentPayment, RentCost, OwnerSettlement, DateRange, CategoryBreakdown } from '../types';
import { formatCurrency, formatDate, getColorForIndex } from '../utils/formatting';

interface PDFData {
  expenses: Expense[];
  dateRange: DateRange;
  householdTotal: number;
  personalTotal: number;
  breakdowns: CategoryBreakdown[];
  totalAmount: number;
}

/**
 * Generate a PDF report from the given expense data, then open the share sheet.
 */
export async function generateExpensePDF(data: PDFData): Promise<string> {
  const {
    expenses,
    dateRange,
    householdTotal,
    personalTotal,
    breakdowns,
    totalAmount,
  } = data;

  const startStr = formatDate(dateRange.startDate);
  const endStr = formatDate(dateRange.endDate);

  const html = `
    <html>
    <head>
      <style>
        body { font-family: -apple-system, Helvetica, Arial, sans-serif; padding: 24px; color: #1a1a2e; }
        h1 { color: #4A90D9; font-size: 28px; }
        h2 { color: #333; font-size: 20px; margin-top: 24px; border-bottom: 2px solid #4A90D9; padding-bottom: 6px; }
        .meta { color: #666; font-size: 14px; margin-bottom: 16px; }
        .summary-grid { display: flex; gap: 16px; margin-bottom: 24px; }
        .summary-card { background: #f5f7fa; border-radius: 12px; padding: 16px; flex: 1; text-align: center; }
        .summary-card .label { font-size: 12px; color: #6b7280; text-transform: uppercase; }
        .summary-card .value { font-size: 24px; font-weight: 800; margin-top: 4px; }
        table { width: 100%; border-collapse: collapse; margin-top: 12px; }
        th { background: #4A90D9; color: #fff; padding: 10px 8px; text-align: left; font-size: 13px; }
        td { padding: 8px; font-size: 13px; border-bottom: 1px solid #e5e7eb; }
        tr:nth-child(even) { background: #f9fafb; }
        .cat-row { display: flex; align-items: center; gap: 8px; padding: 6px 0; }
        .cat-dot { width: 12px; height: 12px; border-radius: 6px; display: inline-block; }
        .footer { margin-top: 32px; text-align: center; color: #9ca3af; font-size: 11px; }
      </style>
    </head>
    <body>
      <h1>Spendee – Expense Report</h1>
      <p class="meta">${startStr} – ${endStr}</p>

      <div class="summary-grid">
        <div class="summary-card">
          <div class="label">Total</div>
          <div class="value">${formatCurrency(totalAmount)}</div>
        </div>
        <div class="summary-card">
          <div class="label">Household</div>
          <div class="value" style="color:#4A90D9">${formatCurrency(householdTotal)}</div>
        </div>
        <div class="summary-card">
          <div class="label">Personal</div>
          <div class="value" style="color:#FF6B6B">${formatCurrency(personalTotal)}</div>
        </div>
      </div>

      <h2>Category Summary</h2>
      ${breakdowns
        .map(
          b => `
        <div class="cat-row">
          <span class="cat-dot" style="background:${b.color}"></span>
          <span style="flex:1">${b.category}</span>
          <span style="font-weight:600">${formatCurrency(b.amount)}</span>
          <span style="color:#6b7280;width:50px;text-align:right">${b.percentage.toFixed(1)}%</span>
        </div>`,
        )
        .join('')}

      <h2>Expense List (${expenses.length} items)</h2>
      <table>
        <tr>
          <th>Date</th>
          <th>Title</th>
          <th>Category</th>
          <th>Type</th>
          <th style="text-align:right">Amount</th>
        </tr>
        ${expenses
          .map(
            e => `
          <tr>
            <td>${formatDate(e.date)}</td>
            <td>${e.title}</td>
            <td>${e.category}</td>
            <td>${e.type}</td>
            <td style="text-align:right;font-weight:600">${formatCurrency(e.amount)}</td>
          </tr>`,
          )
          .join('')}
      </table>

      <div class="footer">
        Generated by Spendee · ${new Date().toLocaleDateString()}
      </div>
    </body>
    </html>
  `;

  const options = {
    html,
    fileName: `Spendee_Report_${startStr}_${endStr}`.replace(/\s/g, '_'),
    directory: 'Documents',
  };

  const file = await RNHTMLtoPDF.convert(options);
  return file.filePath!;
}

// ─── Income PDF ─────────────────────────────────────────────────────────────

interface IncomePDFData {
  incomes: Income[];
  dateRange: DateRange;
  totalAmount: number;
  sourceBreakdowns: CategoryBreakdown[];
}

export async function generateIncomePDF(data: IncomePDFData): Promise<string> {
  const { incomes, dateRange, totalAmount, sourceBreakdowns } = data;
  const startStr = formatDate(dateRange.startDate);
  const endStr = formatDate(dateRange.endDate);

  const cap = (s: string) => s.charAt(0).toUpperCase() + s.slice(1);

  const html = `
    <html>
    <head>
      <style>
        body { font-family: -apple-system, Helvetica, Arial, sans-serif; padding: 24px; color: #1a1a2e; }
        h1 { color: #22C55E; font-size: 28px; }
        h2 { color: #333; font-size: 20px; margin-top: 24px; border-bottom: 2px solid #22C55E; padding-bottom: 6px; }
        .meta { color: #666; font-size: 14px; margin-bottom: 16px; }
        .summary-grid { display: flex; gap: 16px; margin-bottom: 24px; }
        .summary-card { background: #f0fdf4; border-radius: 12px; padding: 16px; flex: 1; text-align: center; }
        .summary-card .label { font-size: 12px; color: #6b7280; text-transform: uppercase; }
        .summary-card .value { font-size: 24px; font-weight: 800; margin-top: 4px; color: #22C55E; }
        table { width: 100%; border-collapse: collapse; margin-top: 12px; }
        th { background: #22C55E; color: #fff; padding: 10px 8px; text-align: left; font-size: 13px; }
        td { padding: 8px; font-size: 13px; border-bottom: 1px solid #e5e7eb; }
        tr:nth-child(even) { background: #f9fafb; }
        .cat-row { display: flex; align-items: center; gap: 8px; padding: 6px 0; }
        .cat-dot { width: 12px; height: 12px; border-radius: 6px; display: inline-block; }
        .footer { margin-top: 32px; text-align: center; color: #9ca3af; font-size: 11px; }
      </style>
    </head>
    <body>
      <h1>Spendee – Income Report</h1>
      <p class="meta">${startStr} – ${endStr}</p>

      <div class="summary-grid">
        <div class="summary-card">
          <div class="label">Total Income</div>
          <div class="value">${formatCurrency(totalAmount)}</div>
        </div>
        <div class="summary-card">
          <div class="label">Entries</div>
          <div class="value" style="color:#333">${incomes.length}</div>
        </div>
      </div>

      <h2>Source Breakdown</h2>
      ${sourceBreakdowns
        .map(
          b => `
        <div class="cat-row">
          <span class="cat-dot" style="background:${b.color}"></span>
          <span style="flex:1">${cap(b.category)}</span>
          <span style="font-weight:600">${formatCurrency(b.amount)}</span>
          <span style="color:#6b7280;width:50px;text-align:right">${b.percentage.toFixed(1)}%</span>
        </div>`,
        )
        .join('')}

      <h2>Income List (${incomes.length} items)</h2>
      <table>
        <tr>
          <th>Date</th>
          <th>Title</th>
          <th>Source</th>
          <th style="text-align:right">Amount</th>
        </tr>
        ${incomes
          .map(
            i => `
          <tr>
            <td>${formatDate(i.date)}</td>
            <td>${i.title}</td>
            <td>${cap(i.source)}</td>
            <td style="text-align:right;font-weight:600;color:#22C55E">+${formatCurrency(i.amount)}</td>
          </tr>`,
          )
          .join('')}
      </table>

      <div class="footer">
        Generated by Spendee · ${new Date().toLocaleDateString()}
      </div>
    </body>
    </html>
  `;

  const options = {
    html,
    fileName: `Spendee_Income_${startStr}_${endStr}`.replace(/\s/g, '_'),
    directory: 'Documents',
  };

  const file = await RNHTMLtoPDF.convert(options);
  return file.filePath!;
}

// ─── Rent Collection PDF ────────────────────────────────────────────────────

interface RentPDFData {
  month: string;
  tenants: Tenant[];
  flats: Flat[];
  owners: Owner[];
  payments: RentPayment[];
  costs: RentCost[];
  ownerSettlements: OwnerSettlement[];
  totalExpected: number;
  totalCollected: number;
  totalCosts: number;
  netIncome: number;
}

export async function generateRentPDF(data: RentPDFData): Promise<string> {
  const {
    month,
    tenants,
    flats,
    owners,
    payments,
    costs,
    ownerSettlements,
    totalExpected,
    totalCollected,
    totalCosts,
    netIncome,
  } = data;
  const getFlatNumber = (tn: Tenant) => flats.find(f => f.id === tn.flatId)?.flatNumber ?? '—';

  const [y, m] = month.split('-').map(Number);
  const monthLabel = new Date(y, m - 1).toLocaleDateString('en-US', {
    month: 'long',
    year: 'numeric',
  });
  const collectionRate =
    totalExpected > 0 ? Math.round((totalCollected / totalExpected) * 100) : 0;

  const cap = (s: string) => s.charAt(0).toUpperCase() + s.slice(1);

  const paidRows = tenants
    .map(tn => {
      const pmt = payments.find(p => p.tenantId === tn.id);
      if (!pmt) return '';
      return `
        <tr>
          <td>${tn.name}</td>
          <td>${getFlatNumber(tn)}</td>
          <td style="text-align:right">${formatCurrency(tn.rentAmount)}</td>
          <td style="text-align:right;color:#22C55E;font-weight:600">${formatCurrency(pmt.amount)}</td>
          <td style="text-align:right;color:#22C55E;font-weight:600">Paid</td>
        </tr>`;
    })
    .join('');

  const unpaidRows = tenants
    .filter(tn => !payments.some(p => p.tenantId === tn.id))
    .map(
      tn => `
        <tr>
          <td>${tn.name}</td>
          <td>${getFlatNumber(tn)}</td>
          <td style="text-align:right">${formatCurrency(tn.rentAmount)}</td>
          <td style="text-align:right;color:#999">–</td>
          <td style="text-align:right;color:#EF4444;font-weight:600">Due</td>
        </tr>`,
    )
    .join('');

  const costRows = costs
    .map(
      c => `
        <tr>
          <td>${formatDate(c.date)}</td>
          <td>${c.title}</td>
          <td>${cap(c.category)}</td>
          <td style="text-align:right;color:#EF4444;font-weight:600">${formatCurrency(c.amount)}</td>
        </tr>`,
    )
    .join('');

  const html = `
    <html>
    <head>
      <style>
        body { font-family: -apple-system, Helvetica, Arial, sans-serif; padding: 24px; color: #1a1a2e; }
        h1 { color: #4A90D9; font-size: 28px; }
        h2 { color: #333; font-size: 20px; margin-top: 24px; border-bottom: 2px solid #4A90D9; padding-bottom: 6px; }
        .meta { color: #666; font-size: 14px; margin-bottom: 16px; }
        .summary-grid { display: flex; gap: 12px; margin-bottom: 24px; flex-wrap: wrap; }
        .summary-card { background: #f5f7fa; border-radius: 12px; padding: 14px; flex: 1; min-width: 120px; text-align: center; }
        .summary-card .label { font-size: 11px; color: #6b7280; text-transform: uppercase; }
        .summary-card .value { font-size: 20px; font-weight: 800; margin-top: 4px; }
        table { width: 100%; border-collapse: collapse; margin-top: 12px; }
        th { background: #4A90D9; color: #fff; padding: 10px 8px; text-align: left; font-size: 13px; }
        td { padding: 8px; font-size: 13px; border-bottom: 1px solid #e5e7eb; }
        tr:nth-child(even) { background: #f9fafb; }
        .footer { margin-top: 32px; text-align: center; color: #9ca3af; font-size: 11px; }
      </style>
    </head>
    <body>
      <h1>Spendee – Rent Collection Report</h1>
      <p class="meta">${monthLabel}</p>

      <div class="summary-grid">
        <div class="summary-card">
          <div class="label">Expected</div>
          <div class="value">${formatCurrency(totalExpected)}</div>
        </div>
        <div class="summary-card">
          <div class="label">Collected</div>
          <div class="value" style="color:#22C55E">${formatCurrency(totalCollected)}</div>
        </div>
        <div class="summary-card">
          <div class="label">Costs</div>
          <div class="value" style="color:#EF4444">${formatCurrency(totalCosts)}</div>
        </div>
        <div class="summary-card">
          <div class="label">Net Income</div>
          <div class="value" style="color:${netIncome >= 0 ? '#22C55E' : '#EF4444'}">
            ${netIncome < 0 ? '-' : ''}${formatCurrency(Math.abs(netIncome))}
          </div>
        </div>
      </div>

      <div class="summary-card" style="margin-bottom:24px">
        <div class="label">Collection Rate</div>
        <div class="value" style="color:${collectionRate >= 80 ? '#22C55E' : collectionRate >= 50 ? '#F59E0B' : '#EF4444'}">${collectionRate}%</div>
      </div>

      <h2>Tenant Status (${tenants.length} tenants)</h2>
      <table>
        <tr>
          <th>Name</th>
          <th>Flat</th>
          <th style="text-align:right">Rent</th>
          <th style="text-align:right">Paid</th>
          <th style="text-align:right">Status</th>
        </tr>
        ${paidRows}${unpaidRows}
      </table>

      ${costs.length > 0 ? `
      <h2>Property Costs (${costs.length} items)</h2>
      <table>
        <tr>
          <th>Date</th>
          <th>Title</th>
          <th>Category</th>
          <th style="text-align:right">Amount</th>
        </tr>
        ${costRows}
      </table>
      ` : ''}

      ${ownerSettlements.length > 0 ? `
      <h2>Owner Statement</h2>
      <table>
        <tr>
          <th>Owner</th>
          <th style="text-align:center">Flats</th>
          <th style="text-align:right">Collected</th>
          <th style="text-align:right">Shared Exp</th>
          <th style="text-align:right">Own Exp</th>
          <th style="text-align:right">Contributed</th>
          <th style="text-align:right">Net</th>
        </tr>
        ${ownerSettlements.map(s => `
          <tr>
            <td>${s.ownerName}</td>
            <td style="text-align:center">${s.flatCount}</td>
            <td style="text-align:right;color:#22C55E;font-weight:600">${formatCurrency(s.totalCollected)}</td>
            <td style="text-align:right;color:#EF4444">${formatCurrency(s.sharedExpenses)}</td>
            <td style="text-align:right;color:#F59E0B">${s.ownExpenses > 0 ? formatCurrency(s.ownExpenses) : '–'}</td>
            <td style="text-align:right;color:#3B82F6">${s.ownContribution > 0 ? formatCurrency(s.ownContribution) : '–'}</td>
            <td style="text-align:right;font-weight:700;color:${s.netAmount >= 0 ? '#22C55E' : '#EF4444'}">${s.netAmount < 0 ? '-' : ''}${formatCurrency(Math.abs(s.netAmount))}</td>
          </tr>`).join('')}
      </table>
      ` : ''}

      <div class="footer">
        Generated by Spendee · ${new Date().toLocaleDateString()}
      </div>
    </body>
    </html>
  `;

  const options = {
    html,
    fileName: `Spendee_Rent_${month}`.replace(/\s/g, '_'),
    directory: 'Documents',
  };

  const file = await RNHTMLtoPDF.convert(options);
  return file.filePath!;
}

// ─── Combined Expense + Income PDF ─────────────────────────────────────────

interface CombinedPDFData {
  expenses: Expense[];
  incomes: Income[];
  dateRange: DateRange;
  totalExpenses: number;
  totalIncome: number;
  expenseBreakdowns: CategoryBreakdown[];
  sourceBreakdowns: CategoryBreakdown[];
}

export async function generateCombinedPDF(data: CombinedPDFData): Promise<string> {
  const {
    expenses,
    incomes,
    dateRange,
    totalExpenses,
    totalIncome,
    expenseBreakdowns,
    sourceBreakdowns,
  } = data;

  const balance = totalIncome - totalExpenses;
  const startStr = formatDate(dateRange.startDate);
  const endStr = formatDate(dateRange.endDate);
  const cap = (s: string) => s.charAt(0).toUpperCase() + s.slice(1);

  const expenseCatRows = expenseBreakdowns
    .map(
      b => `
      <div class="cat-row">
        <span class="cat-dot" style="background:${b.color}"></span>
        <span style="flex:1">${cap(b.category)}</span>
        <span style="font-weight:600;color:#EF4444">${formatCurrency(b.amount)}</span>
        <span style="color:#6b7280;width:50px;text-align:right">${b.percentage.toFixed(1)}%</span>
      </div>`,
    )
    .join('');

  const incomeSrcRows = sourceBreakdowns
    .map(
      b => `
      <div class="cat-row">
        <span class="cat-dot" style="background:${b.color}"></span>
        <span style="flex:1">${cap(b.category)}</span>
        <span style="font-weight:600;color:#22C55E">${formatCurrency(b.amount)}</span>
        <span style="color:#6b7280;width:50px;text-align:right">${b.percentage.toFixed(1)}%</span>
      </div>`,
    )
    .join('');

  const expenseRows = expenses
    .map(
      e => `
      <tr>
        <td>${formatDate(e.date)}</td>
        <td>${e.title}</td>
        <td>${cap(e.category)}</td>
        <td style="text-align:right;color:#EF4444;font-weight:600">-${formatCurrency(e.amount)}</td>
      </tr>`,
    )
    .join('');

  const incomeRows = incomes
    .map(
      i => `
      <tr>
        <td>${formatDate(i.date)}</td>
        <td>${i.title}</td>
        <td>${cap(i.source)}</td>
        <td style="text-align:right;color:#22C55E;font-weight:600">+${formatCurrency(i.amount)}</td>
      </tr>`,
    )
    .join('');

  const html = `
    <html>
    <head>
      <style>
        body { font-family: -apple-system, Helvetica, Arial, sans-serif; padding: 24px; color: #1a1a2e; }
        h1 { color: #4A90D9; font-size: 28px; }
        h2 { color: #333; font-size: 20px; margin-top: 28px; border-bottom: 2px solid #e5e7eb; padding-bottom: 6px; }
        h2.exp { border-color: #EF4444; }
        h2.inc { border-color: #22C55E; }
        .meta { color: #666; font-size: 14px; margin-bottom: 16px; }
        .summary-grid { display: flex; gap: 12px; margin-bottom: 24px; }
        .summary-card { background: #f5f7fa; border-radius: 12px; padding: 14px; flex: 1; text-align: center; }
        .summary-card .label { font-size: 11px; color: #6b7280; text-transform: uppercase; }
        .summary-card .value { font-size: 20px; font-weight: 800; margin-top: 4px; }
        .cat-row { display: flex; align-items: center; gap: 8px; padding: 6px 0; font-size:13px; }
        .cat-dot { width: 12px; height: 12px; border-radius: 6px; display: inline-block; flex-shrink:0; }
        table { width: 100%; border-collapse: collapse; margin-top: 12px; }
        th { padding: 10px 8px; text-align: left; font-size: 13px; color: #fff; }
        th.exp-th { background: #EF4444; }
        th.inc-th { background: #22C55E; }
        td { padding: 8px; font-size: 13px; border-bottom: 1px solid #e5e7eb; }
        tr:nth-child(even) { background: #f9fafb; }
        .footer { margin-top: 32px; text-align: center; color: #9ca3af; font-size: 11px; }
      </style>
    </head>
    <body>
      <h1>Spendee – Expense &amp; Income Report</h1>
      <p class="meta">${startStr} – ${endStr}</p>

      <div class="summary-grid">
        <div class="summary-card">
          <div class="label">Total Income</div>
          <div class="value" style="color:#22C55E">${formatCurrency(totalIncome)}</div>
        </div>
        <div class="summary-card">
          <div class="label">Total Expenses</div>
          <div class="value" style="color:#EF4444">${formatCurrency(totalExpenses)}</div>
        </div>
        <div class="summary-card">
          <div class="label">Balance</div>
          <div class="value" style="color:${balance >= 0 ? '#22C55E' : '#EF4444'}">
            ${balance < 0 ? '-' : ''}${formatCurrency(Math.abs(balance))}
          </div>
        </div>
      </div>

      <h2 class="exp">Expense Breakdown</h2>
      ${expenseCatRows}

      <h2 class="inc">Income Sources</h2>
      ${incomeSrcRows}

      <h2 class="exp">Expenses (${expenses.length} items)</h2>
      <table>
        <tr>
          <th class="exp-th">Date</th>
          <th class="exp-th">Title</th>
          <th class="exp-th">Category</th>
          <th class="exp-th" style="text-align:right">Amount</th>
        </tr>
        ${expenseRows}
      </table>

      <h2 class="inc">Income (${incomes.length} items)</h2>
      <table>
        <tr>
          <th class="inc-th">Date</th>
          <th class="inc-th">Title</th>
          <th class="inc-th">Source</th>
          <th class="inc-th" style="text-align:right">Amount</th>
        </tr>
        ${incomeRows}
      </table>

      <div class="footer">
        Generated by Spendee · ${new Date().toLocaleDateString()}
      </div>
    </body>
    </html>
  `;

  const options = {
    html,
    fileName: `Spendee_Combined_${startStr}_${endStr}`.replace(/\s/g, '_'),
    directory: 'Documents',
  };

  const file = await RNHTMLtoPDF.convert(options);
  return file.filePath!;
}

// ─── Multi-Month Rent PDF ───────────────────────────────────────────────────

interface MultiMonthRentPDFData {
  months: string[]; // array of 'YYYY-MM' keys
  tenantsByMonth: Record<string, Tenant[]>; // correct tenants per month
  flats: Flat[];
  paymentsByMonth: Record<string, RentPayment[]>;
  costsByMonth: Record<string, RentCost[]>;
}

export async function generateMultiMonthRentPDF(data: MultiMonthRentPDFData): Promise<string> {
  const { months, tenantsByMonth, flats, paymentsByMonth, costsByMonth } = data;
  const getFlatNumber = (tn: Tenant) => flats.find(f => f.id === tn.flatId)?.flatNumber ?? '—';

  const formatMonth = (m: string) => {
    const [y, mo] = m.split('-').map(Number);
    return new Date(y, mo - 1).toLocaleDateString('en-US', { month: 'long', year: 'numeric' });
  };

  const cap = (s: string) => s.charAt(0).toUpperCase() + s.slice(1);

  let grandCollected = 0;
  let grandExpected = 0;
  let grandCosts = 0;

  const monthSections = months.map(month => {
    const tenants = tenantsByMonth[month] || [];
    const payments = paymentsByMonth[month] || [];
    const costs = costsByMonth[month] || [];
    const totalExpected = tenants.reduce((s, t) => s + t.rentAmount, 0);
    const totalCollected = payments.reduce((s, p) => s + p.amount, 0);
    const totalCosts = costs.reduce((s, c) => s + c.amount, 0);
    const netIncome = totalCollected - totalCosts;

    grandCollected += totalCollected;
    grandExpected += totalExpected;
    grandCosts += totalCosts;

    const tenantRows = tenants.map(tn => {
      const pmt = payments.find(p => p.tenantId === tn.id);
      const paid = pmt ? pmt.amount : 0;
      const due = pmt ? (pmt.dueAmount || 0) : tn.rentAmount;
      const status = pmt ? (due > 0 ? 'Partial' : 'Paid') : 'Due';
      const statusColor = status === 'Paid' ? '#22C55E' : status === 'Partial' ? '#F59E0B' : '#EF4444';
      return `
        <tr>
          <td>${tn.name}</td>
          <td>${getFlatNumber(tn)}</td>
          <td style="text-align:right">${formatCurrency(tn.rentAmount)}</td>
          <td style="text-align:right;color:${paid > 0 ? '#22C55E' : '#999'};font-weight:600">${paid > 0 ? formatCurrency(paid) : '–'}</td>
          <td style="text-align:right;color:${due > 0 ? '#EF4444' : '#999'}">${due > 0 ? formatCurrency(due) : '–'}</td>
          <td style="color:${statusColor};font-weight:600">${status}</td>
        </tr>`;
    }).join('');

    const costRows = costs.map(c => `
      <tr>
        <td>${formatDate(c.date)}</td>
        <td>${c.title}</td>
        <td>${cap(c.category)}</td>
        <td style="text-align:right;color:#EF4444;font-weight:600">${formatCurrency(c.amount)}</td>
      </tr>`).join('');

    return `
      <div class="month-section">
        <h2>${formatMonth(month)}</h2>
        <div class="summary-grid">
          <div class="summary-card">
            <div class="label">Expected</div>
            <div class="value">${formatCurrency(totalExpected)}</div>
          </div>
          <div class="summary-card">
            <div class="label">Collected</div>
            <div class="value" style="color:#22C55E">${formatCurrency(totalCollected)}</div>
          </div>
          <div class="summary-card">
            <div class="label">Costs</div>
            <div class="value" style="color:#EF4444">${formatCurrency(totalCosts)}</div>
          </div>
          <div class="summary-card">
            <div class="label">Net</div>
            <div class="value" style="color:${netIncome >= 0 ? '#22C55E' : '#EF4444'}">${netIncome < 0 ? '-' : ''}${formatCurrency(Math.abs(netIncome))}</div>
          </div>
        </div>

        <h3>Tenants (${tenants.length})</h3>
        <table>
          <tr>
            <th>Name</th><th>Flat</th><th style="text-align:right">Rent</th><th style="text-align:right">Paid</th><th style="text-align:right">Due</th><th>Status</th>
          </tr>
          ${tenantRows}
        </table>

        ${costs.length > 0 ? `
        <h3>Costs (${costs.length})</h3>
        <table>
          <tr><th>Date</th><th>Title</th><th>Category</th><th style="text-align:right">Amount</th></tr>
          ${costRows}
        </table>` : ''}
      </div>
    `;
  }).join('');

  const grandNet = grandCollected - grandCosts;
  const startLabel = formatMonth(months[0]);
  const endLabel = formatMonth(months[months.length - 1]);

  const html = `
    <html>
    <head>
      <style>
        body { font-family: -apple-system, Helvetica, Arial, sans-serif; padding: 24px; color: #1a1a2e; }
        h1 { color: #4A90D9; font-size: 28px; }
        h2 { color: #4A90D9; font-size: 20px; margin-top: 32px; border-bottom: 2px solid #4A90D9; padding-bottom: 6px; }
        h3 { color: #333; font-size: 16px; margin-top: 16px; }
        .meta { color: #666; font-size: 14px; margin-bottom: 16px; }
        .summary-grid { display: flex; gap: 10px; margin-bottom: 16px; flex-wrap: wrap; }
        .summary-card { background: #f5f7fa; border-radius: 10px; padding: 12px; flex: 1; min-width: 100px; text-align: center; }
        .summary-card .label { font-size: 10px; color: #6b7280; text-transform: uppercase; }
        .summary-card .value { font-size: 18px; font-weight: 800; margin-top: 4px; }
        .grand-summary { background: #1E3A5F; color: #fff; border-radius: 14px; padding: 20px; margin-bottom: 24px; }
        .grand-summary .label { color: rgba(255,255,255,0.6); font-size: 10px; text-transform: uppercase; }
        .grand-summary .value { color: #fff; font-size: 22px; font-weight: 800; }
        table { width: 100%; border-collapse: collapse; margin-top: 8px; }
        th { background: #4A90D9; color: #fff; padding: 8px 6px; text-align: left; font-size: 12px; }
        td { padding: 7px 6px; font-size: 12px; border-bottom: 1px solid #e5e7eb; }
        tr:nth-child(even) { background: #f9fafb; }
        .month-section { page-break-inside: avoid; }
        .footer { margin-top: 32px; text-align: center; color: #9ca3af; font-size: 11px; }
      </style>
    </head>
    <body>
      <h1>Spendee – Multi-Month Rent Report</h1>
      <p class="meta">${startLabel} – ${endLabel} (${months.length} months)</p>

      <div class="grand-summary">
        <div class="summary-grid">
          <div style="flex:1;text-align:center">
            <div class="label">Total Expected</div>
            <div class="value">${formatCurrency(grandExpected)}</div>
          </div>
          <div style="flex:1;text-align:center">
            <div class="label">Total Collected</div>
            <div class="value" style="color:#4ADE80">${formatCurrency(grandCollected)}</div>
          </div>
          <div style="flex:1;text-align:center">
            <div class="label">Total Costs</div>
            <div class="value" style="color:#F87171">${formatCurrency(grandCosts)}</div>
          </div>
          <div style="flex:1;text-align:center">
            <div class="label">Grand Net</div>
            <div class="value" style="color:${grandNet >= 0 ? '#4ADE80' : '#F87171'}">${grandNet < 0 ? '-' : ''}${formatCurrency(Math.abs(grandNet))}</div>
          </div>
        </div>
      </div>

      ${monthSections}

      <div class="footer">
        Generated by Spendee · ${new Date().toLocaleDateString()}
      </div>
    </body>
    </html>
  `;

  const options = {
    html,
    fileName: `Spendee_Rent_${months[0]}_to_${months[months.length - 1]}`.replace(/\s/g, '_'),
    directory: 'Documents',
  };

  const file = await RNHTMLtoPDF.convert(options);
  return file.filePath!;
}

/**
 * Share the generated PDF via the native share sheet.
 */
export async function sharePDF(filePath: string): Promise<void> {
  try {
    await Share.open({
      url: `file://${filePath}`,
      type: 'application/pdf',
      title: 'Spendee Expense Report',
    });
  } catch (e: any) {
    // User dismissed the share sheet — not an error
    if (e?.message?.includes('User did not share') || e?.message?.includes('CANCELLED')) {
      return;
    }
    throw e;
  }
}

/**
 * Open the generated PDF with the device's default viewer.
 */
export async function openPDF(filePath: string): Promise<void> {
  await Share.open({
    url: `file://${filePath}`,
    type: 'application/pdf',
    showAppsToView: true,
  });
}
